Add replace_whitespace function

diff --git a/bash/functions b/bash/functions
--- a/bash/functions
+++ b/bash/functions
@@ -1,6 +1,43 @@
 #!/bin/bash
 
 ###########################
+# Utility
+###########################
+
+# Replaces whitespaces with underscores for
+# every file in the specified directory.
+function replace_whitespace {
+  local renamed=0
+  if [ "${1}" ] && [ -d "${1}" ]; then
+    for filename in "${1}"/*; do
+      echo "${filename}" | grep -q " "
+      if [ $? -eq 0 ]; then
+        mv "${filename}" $(echo "${filename}" | sed -e "s/ /_/g")
+        let renamed+=1
+      fi
+    done
+    echo "${renamed} file(s) renamed."
+  else
+    echo "Invalid path."
+  fi
+}
+
+###########################
+# Funny Or Die
+###########################
+
+function fod {
+  cd "${HOME}/Dev/funnyordie"
+  if [[ $1 == "restart" || $1 == "r" ]]
+  then
+    sudo powify server restart
+  elif [[ $1 == "t" || $1 == "tail" ]]
+  then
+    tail -f "${HOME}/Dev/funnyordie/log/development.log"
+  fi
+}
+
+###########################
 # Dotfiles
 ###########################
 
@@ -34,18 +71,3 @@ function dotfiles {
 }
 
 #   ln -s "${DOTFILES}/config/.gitconfig" "${HOME}/.gitconfig"
-
-###########################
-# Funny Or Die
-###########################
-
-function fod {
-  cd "${HOME}/Dev/funnyordie"
-  if [[ $1 == "restart" || $1 == "r" ]]
-  then
-    sudo powify server restart
-  elif [[ $1 == "t" || $1 == "tail" ]]
-  then
-    tail -f "${HOME}/Dev/funnyordie/log/development.log"
-  fi
-}
